import { defineConfig, withBase } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  lang: 'ja',
  srcDir: './docs',
  outDir: '../raia-engine.github.io/docs',
  ignoreDeadLinks: true,
  title: "RaiaEngine",
  description: "WebAPI-compatible framework for building apps that run in native environments.",
  lastUpdated: true,
  themeConfig: {
    search: {
      provider: 'local'
    },
    editLink: {
      pattern: 'https://github.com/raia-engine/raia-document/edit/main/docs/:path'
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/dolphilia/raia' }
    ],
    nav: [
      { text: 'ホーム', link: '/'},
      { text: 'チュートリアル', link: '/tutorial/'},
      { text: 'ドキュメント', link: '/document'},
      { text: 'リファレンス', items: [
        {text: 'LuaJITライブラリ', link: '/reference/built_in/'},
        {text: 'Lua/Cライブラリ', link: '/reference/lua_c/'},
      ]},
      { text: 'リソース', items: [
        {text: 'cosmopolitan', link: '/resource/cosmopolitan/'},
        {text: 'duktape', link: '/resource/duktape/'},
        {text: 'GLFW', link: '/resource/glfw/'},
        {text: 'ImGui', link: '/resource/imgui/'},
        {text: 'libffi', link: '/resource/libffi/'},
        {text: 'Lua', link: '/resource/lua/'},
        {text: 'LuaJIT', link: '/resource/luajit/'},
        {text: 'miniaudio', link: '/resource/miniaudio/'},
        {text: 'Skia', link: '/resource/skia/'},
        {text: 'stb', link: '/resource/stb/'},
        {text: 'Terra', link: '/resource/terra/'},
        {text: 'uthash', link: '/resource/uthash/'},
        {text: 'yyjson', link: '/resource/yyjson/'},
      ]},
      { text: 'ダウンロード', link: '/download/'},
    ],
    sidebar: {
      '/download/': [
        {
          text: 'ダウンロード',
          items: [
            { text: 'はじめに', link: '/download/' },
          ]
        }
      ],
      '/usage/':[
        {
          text: '使い方',
          collapsed: false,
          items: [
            { text: 'はじめに', link: '/usage/' },
            { text: 'インストールとセットアップ', link: '/usage/setup'}
          ]
        },
        {
          text: 'チュートリアル',
          collapsed: false,
          items: [
            { 
              text: 'Windows編', 
              collapsed: false,
              items: [
                { text:'Hello World', link:'/usage/tutorial/windows/helloworld'},
                { text:'図形を描画する', link:'/usage/tutorial/windows/shape'},
                { text:'画像を表示する', link:'/usage/tutorial/windows/image'},
                { text:'サーフェスに描画する', link:'/usage/tutorial/windows/surface'},
                { text:'メインループを使う', link:'/usage/tutorial/windows/mainloop'},
                { text:'入力を検知する', link:'/usage/tutorial/windows/input'},
              ] 
            },
            { text: 'macOS編', link: '/usage/tutorial/macos/' },
            { text: 'Linux編', link: '/usage/tutorial/linux/' }
          ]
        },
      ],
      '/reference/built_in': [
        {
          text: 'はじめに',
          collapsed: false,
          items: [
            { text: 'LuaJITライブラリ', link: '/reference/built_in/' },
          ]
        },
        {
          text: 'グローバル変数',
          collapsed: true,
          items: [
            { text: '_G', link: '/reference/built_in/global/_g.md'},
            { text: '_VERSION', link: '/reference/built_in/global/_version.md'},
          ]
        },
        {
          text: '基本関数',
          collapsed: true,
          items: [
            { text: 'assert', link: '/reference/built_in/std/assert.md'},
            { text: 'collectgarbage', link: '/reference/built_in/std/collectgarbage.md'},
            { text: 'dofile', link: '/reference/built_in/std/dofile.md'},
            { text: 'error', link: '/reference/built_in/std/error.md'},
            { text: 'getfenv', link: '/reference/built_in/std/getfenv.md'},
            { text: 'getmetatable', link: '/reference/built_in/std/getmetatable.md'},
            { text: 'ipairs', link: '/reference/built_in/std/ipairs.md'},
            { text: 'load', link: '/reference/built_in/std/load.md'},
            { text: 'loadfile', link: '/reference/built_in/std/loadfile.md'},
            { text: 'loadstring', link: '/reference/built_in/std/loadstring.md'},
            { text: 'next', link: '/reference/built_in/std/next.md'},
            { text: 'pairs', link: '/reference/built_in/std/pairs.md'},
            { text: 'pcall', link: '/reference/built_in/std/pcall.md'},
            { text: 'print', link: '/reference/built_in/std/print.md'},
            { text: 'rawequal', link: '/reference/built_in/std/rawequal.md'},
            { text: 'rawget', link: '/reference/built_in/std/rawget.md'},
            { text: 'rawset', link: '/reference/built_in/std/rawset.md'},
            { text: 'select', link: '/reference/built_in/std/select.md'},
            { text: 'setfenv', link: '/reference/built_in/std/setfenv.md'},
            { text: 'setmetatable', link: '/reference/built_in/std/setmetatable.md'},
            { text: 'tonumber', link: '/reference/built_in/std/tonumber.md'},
            { text: 'tostring', link: '/reference/built_in/std/tostring.md'},
            { text: 'type', link: '/reference/built_in/std/type.md'},
            { text: 'unpack', link: '/reference/built_in/std/unpack.md'},
            { text: 'xpcall', link: '/reference/built_in/std/xpcall.md'},
          ]
        },
        {
          text: 'コルーチン操作',
          collapsed: true,
          items: [
            { text: 'coroutine.create', link: '/reference/built_in/coroutine/create.md'},
            { text: 'coroutine.resume', link: '/reference/built_in/coroutine/resume.md'},
            { text: 'coroutine.running', link: '/reference/built_in/coroutine/running.md'},
            { text: 'coroutine.status', link: '/reference/built_in/coroutine/status.md'},
            { text: 'coroutine.wrap', link: '/reference/built_in/coroutine/wrap.md'},
            { text: 'coroutine.yield', link: '/reference/built_in/coroutine/yield.md'},
            { text: 'coroutine.isyieldable', link: '/reference/built_in/coroutine/isyieldable.md'},
          ]
        },
        {
          text: 'モジュール',
          collapsed: true,
          items: [
            { text: 'module', link: '/reference/built_in/package/module.md'},
            { text: 'require', link: '/reference/built_in/package/require.md'},
            { text: 'package.cpath', link: '/reference/built_in/package/cpath.md'},
            { text: 'package.loaded', link: '/reference/built_in/package/loaded.md'},
            { text: 'package.loaders', link: '/reference/built_in/package/loaders.md'},
            { text: 'package.loadlib', link: '/reference/built_in/package/loadlib.md'},
            { text: 'package.path', link: '/reference/built_in/package/path.md'},
            { text: 'package.preload', link: '/reference/built_in/package/preload.md'},
            { text: 'package.seeall', link: '/reference/built_in/package/seeall.md'},
            { text: 'package.searchpath', link: '/reference/built_in/package/searchpath.md'},
          ]
        },
        {
          text: '文字列操作',
          collapsed: true,
          items: [
            { text: 'string.byte', link: '/reference/built_in/string/byte.md'},
            { text: 'string.char', link: '/reference/built_in/string/char.md'},
            { text: 'string.dump', link: '/reference/built_in/string/dump.md'},
            { text: 'string.find', link: '/reference/built_in/string/find.md'},
            { text: 'string.format', link: '/reference/built_in/string/format.md'},
            { text: 'string.gmatch', link: '/reference/built_in/string/gmatch.md'},
            { text: 'string.gsub', link: '/reference/built_in/string/gsub.md'},
            { text: 'string.len', link: '/reference/built_in/string/len.md'},
            { text: 'string.lower', link: '/reference/built_in/string/lower.md'},
            { text: 'string.match', link: '/reference/built_in/string/match.md'},
            { text: 'string.rep', link: '/reference/built_in/string/rep.md'},
            { text: 'string.reverse', link: '/reference/built_in/string/reverse.md'},
            { text: 'string.sub', link: '/reference/built_in/string/sub.md'},
            { text: 'string.upper', link: '/reference/built_in/string/upper.md'},
          ]
        },
        {
          text: 'テーブル操作',
          collapsed: true,
          items: [
            { text: 'table.concat', link: '/reference/built_in/table/concat.md'},
            { text: 'table.insert', link: '/reference/built_in/table/insert.md'},
            { text: 'table.maxn', link: '/reference/built_in/table/maxn.md'},
            { text: 'table.remove', link: '/reference/built_in/table/remove.md'},
            { text: 'table.sort', link: '/reference/built_in/table/sort.md'},
            { text: 'table.new', link: '/reference/built_in/table/new.md'},
            { text: 'table.clear', link: '/reference/built_in/table/clear.md'},
            { text: 'table.move', link: '/reference/built_in/table/move.md'},
          ]
        },
        {
          text: '数学関数',
          collapsed: true,
          items: [
            { text: 'math.abs', link: '/reference/built_in/math/abs.md'},
            { text: 'math.acos', link: '/reference/built_in/math/acos.md'},
            { text: 'math.asin', link: '/reference/built_in/math/asin.md'},
            { text: 'math.atan', link: '/reference/built_in/math/atan.md'},
            { text: 'math.atan2', link: '/reference/built_in/math/atan2.md'},
            { text: 'math.ceil', link: '/reference/built_in/math/ceil.md'},
            { text: 'math.cos', link: '/reference/built_in/math/cos.md'},
            { text: 'math.cosh', link: '/reference/built_in/math/cosh.md'},
            { text: 'math.deg', link: '/reference/built_in/math/deg.md'},
            { text: 'math.exp', link: '/reference/built_in/math/exp.md'},
            { text: 'math.floor', link: '/reference/built_in/math/floor.md'},
            { text: 'math.fmod', link: '/reference/built_in/math/fmod.md'},
            { text: 'math.frexp', link: '/reference/built_in/math/frexp.md'},
            { text: 'math.huge', link: '/reference/built_in/math/huge.md'},
            { text: 'math.ldexp', link: '/reference/built_in/math/ldexp.md'},
            { text: 'math.log', link: '/reference/built_in/math/log.md'},
            { text: 'math.log10', link: '/reference/built_in/math/log10.md'},
            { text: 'math.max', link: '/reference/built_in/math/max.md'},
            { text: 'math.min', link: '/reference/built_in/math/min.md'},
            { text: 'math.modf', link: '/reference/built_in/math/modf.md'},
            { text: 'math.pi', link: '/reference/built_in/math/pi.md'},
            { text: 'math.pow', link: '/reference/built_in/math/pow.md'},
            { text: 'math.rad', link: '/reference/built_in/math/rad.md'},
            { text: 'math.random', link: '/reference/built_in/math/random.md'},
            { text: 'math.randomseed', link: '/reference/built_in/math/randomseed.md'},
            { text: 'math.sin', link: '/reference/built_in/math/sin.md'},
            { text: 'math.sinh', link: '/reference/built_in/math/sinh.md'},
            { text: 'math.sqrt', link: '/reference/built_in/math/sqrt.md'},
            { text: 'math.tan', link: '/reference/built_in/math/tan.md'},
            { text: 'math.tanh', link: '/reference/built_in/math/tanh.md'},
          ]
        },
        {
          text: '入出力機能',
          collapsed: true,
          items: [
            { text: 'io.close', link: '/reference/built_in/io/close.md'},
            { text: 'io.flush', link: '/reference/built_in/io/flush.md'},
            { text: 'io.input', link: '/reference/built_in/io/input.md'},
            { text: 'io.lines', link: '/reference/built_in/io/lines.md'},
            { text: 'io.open', link: '/reference/built_in/io/open.md'},
            { text: 'io.output', link: '/reference/built_in/io/output.md'},
            { text: 'io.popen', link: '/reference/built_in/io/popen.md'},
            { text: 'io.read', link: '/reference/built_in/io/read.md'},
            { text: 'io.tmpfile', link: '/reference/built_in/io/tmpfile.md'},
            { text: 'io.type', link: '/reference/built_in/io/type.md'},
            { text: 'io.write', link: '/reference/built_in/io/write.md'},
            { text: 'file:close', link: '/reference/built_in/io/file_close.md'},
            { text: 'file:flush', link: '/reference/built_in/io/file_flush.md'},
            { text: 'file:lines', link: '/reference/built_in/io/file_lines.md'},
            { text: 'file:read', link: '/reference/built_in/io/file_read.md'},
            { text: 'file:seek', link: '/reference/built_in/io/file_seek.md'},
            { text: 'file:setvbuf', link: '/reference/built_in/io/file_setvbuf.md'},
            { text: 'file:write', link: '/reference/built_in/io/file_write.md'},
          ]
        },
        {
          text: 'OSの機能',
          collapsed: true,
          items: [
            { text: 'os.clock', link: '/reference/built_in/os/clock.md'},
            { text: 'os.date', link: '/reference/built_in/os/date.md'},
            { text: 'os.difftime', link: '/reference/built_in/os/difftime.md'},
            { text: 'os.execute', link: '/reference/built_in/os/execute.md'},
            { text: 'os.exit', link: '/reference/built_in/os/exit.md'},
            { text: 'os.getenv', link: '/reference/built_in/os/getenv.md'},
            { text: 'os.remove', link: '/reference/built_in/os/remove.md'},
            { text: 'os.rename', link: '/reference/built_in/os/rename.md'},
            { text: 'os.setlocale', link: '/reference/built_in/os/setlocale.md'},
            { text: 'os.time', link: '/reference/built_in/os/time.md'},
            { text: 'os.tmpname', link: '/reference/built_in/os/tmpname.md'},
          ]
        },
        {
          text: 'デバッグ機能',
          collapsed: true,
          items: [
            { text: 'debug.debug', link: '/reference/built_in/debug/debug.md'},
            { text: 'debug.getfenv', link: '/reference/built_in/debug/getfenv.md'},
            { text: 'debug.gethook', link: '/reference/built_in/debug/gethook.md'},
            { text: 'debug.getinfo', link: '/reference/built_in/debug/getinfo.md'},
            { text: 'debug.getlocal', link: '/reference/built_in/debug/getlocal.md'},
            { text: 'debug.getmetatable', link: '/reference/built_in/debug/getmetatable.md'},
            { text: 'debug.getregistry', link: '/reference/built_in/debug/getregistry.md'},
            { text: 'debug.getupvalue', link: '/reference/built_in/debug/getupvalue.md'},
            { text: 'debug.setfenv', link: '/reference/built_in/debug/setfenv.md'},
            { text: 'debug.sethook', link: '/reference/built_in/debug/sethook.md'},
            { text: 'debug.setlocal', link: '/reference/built_in/debug/setlocal.md'},
            { text: 'debug.setmetatable', link: '/reference/built_in/debug/setmetatable.md'},
            { text: 'debug.setupvalue', link: '/reference/built_in/debug/setupvalue.md'},
            { text: 'debug.traceback', link: '/reference/built_in/debug/traceback.md'},
            { text: 'debug.upvalueid', link: '/reference/built_in/debug/upvalueid.md'},
            { text: 'debug.upvaluejoin', link: '/reference/built_in/debug/upvaluejoin.md'},
          ]
        },
        {
          text: 'ビット操作',
          collapsed: true,
          items: [
            { text: 'bit.tobit', link: '/reference/built_in/bit/tobit.md'},
            { text: 'bit.tohex', link: '/reference/built_in/bit/tohex.md'},
            { text: 'bit.bnot', link: '/reference/built_in/bit/bnot.md'},
            { text: 'bit.band', link: '/reference/built_in/bit/band.md'},
            { text: 'bit.bor', link: '/reference/built_in/bit/bor.md'},
            { text: 'bit.bxor', link: '/reference/built_in/bit/bxor.md'},
            { text: 'bit.lshift', link: '/reference/built_in/bit/lshift.md'},
            { text: 'bit.rshift', link: '/reference/built_in/bit/rshift.md'},
            { text: 'bit.arshift', link: '/reference/built_in/bit/arshift.md'},
            { text: 'bit.rol', link: '/reference/built_in/bit/rol.md'},
            { text: 'bit.ror', link: '/reference/built_in/bit/ror.md'},
            { text: 'bit.bswap', link: '/reference/built_in/bit/bswap.md'},
          ]
        },
        {
          text: 'FFI',
          collapsed: true,
          items: [
            { text: 'ffi.os', link: '/reference/built_in/ffi/os.md'},
            { text: 'ffi.arch', link: '/reference/built_in/ffi/arch.md'},
            { text: 'ffi.cdef', link: '/reference/built_in/ffi/cdef.md'},
            { text: 'ffi.C', link: '/reference/built_in/ffi/c.md'},
            { text: 'ffi.load', link: '/reference/built_in/ffi/load.md'},
            { text: 'ffi.new', link: '/reference/built_in/ffi/new.md'},
            { text: 'ctype', link: '/reference/built_in/ffi/ctype.md'},
            { text: 'ffi.typeof', link: '/reference/built_in/ffi/typeof.md'},
            { text: 'ffi.cast', link: '/reference/built_in/ffi/cast.md'},
            { text: 'ffi.metatype', link: '/reference/built_in/ffi/metatype.md'},
            { text: 'ffi.gc', link: '/reference/built_in/ffi/gc.md'},
            { text: 'ffi.sizeof', link: '/reference/built_in/ffi/sizeof.md'},
            { text: 'ffi.alignof', link: '/reference/built_in/ffi/alignof.md'},
            { text: 'ffi.offsetof', link: '/reference/built_in/ffi/offsetof.md'},
            { text: 'ffi.errno', link: '/reference/built_in/ffi/errno.md'},
            { text: 'ffi.string', link: '/reference/built_in/ffi/string.md'},
            { text: 'ffi.copy', link: '/reference/built_in/ffi/copy.md'},
            { text: 'ffi.fill', link: '/reference/built_in/ffi/fill.md'},
            { text: 'ffi.abi', link: '/reference/built_in/ffi/abi.md'},
            { text: 'cb:free', link: '/reference/built_in/ffi/cb_free.md'},
            { text: 'cb:set', link: '/reference/built_in/ffi/cb_set.md'},
          ]
        },
        {
          text: '文字列バッファ',
          collapsed: true,
          items: [
            { text: 'buffer.new', link: '/reference/built_in/string_buffer/new.md' },
            { text: 'buf:reset', link: '/reference/built_in/string_buffer/buf_reset.md' },
            { text: 'buf:free', link: '/reference/built_in/string_buffer/buf_free.md' },
            { text: 'buf:put', link: '/reference/built_in/string_buffer/buf_put.md' },
            { text: 'buf:putf', link: '/reference/built_in/string_buffer/buf_putf.md' },
            { text: 'buf:putcdata', link: '/reference/built_in/string_buffer/buf_putcdata.md' },
            { text: 'buf:set', link: '/reference/built_in/string_buffer/buf_set.md' },
            { text: 'buf:reserve', link: '/reference/built_in/string_buffer/buf_reserve.md' },
            { text: 'buf:skip', link: '/reference/built_in/string_buffer/buf_skip.md' },
            { text: 'buf:get', link: '/reference/built_in/string_buffer/buf_get.md' },
            { text: 'buf:tostring', link: '/reference/built_in/string_buffer/buf_tostring.md' },
            { text: 'buf:ref', link: '/reference/built_in/string_buffer/buf_ref.md' },
            { text: 'buffer.encode', link: '/reference/built_in/string_buffer/encode.md' },
            { text: 'buffer.decode', link: '/reference/built_in/string_buffer/decode.md' },
          ]
        },
        {
          text: 'JIT',
          collapsed: true,
          items: [
            { text: 'jit.version', link: '/reference/built_in/jit/version.md'},
            { text: 'jit.version_num', link: '/reference/built_in/jit/version_num.md'},
            { text: 'jit.os', link: '/reference/built_in/jit/os.md'},
            { text: 'jit.arch', link: '/reference/built_in/jit/arch.md'},
            { text: 'jit.on', link: '/reference/built_in/jit/on.md'},
            { text: 'jit.off', link: '/reference/built_in/jit/off.md'},
            { text: 'jit.flush', link: '/reference/built_in/jit/flush.md'},
            { text: 'jit.status', link: '/reference/built_in/jit/status.md'},
          ]
        },
      ],
      '/reference/lua_c': [
        {
          text: 'はじめに',
          collapsed: false,
          items: [
            { text: 'Lua/Cライブラリ', link: '/reference/lua_c/' },
          ]
        },
        {
          text: '型',
          collapsed: true,
          items: [
            { text:'lua_Alloc', link: '/reference/lua_c/lua_Alloc.md'},
            { text:'lua_CFunction', link: '/reference/lua_c/lua_CFunction.md'},
            { text:'lua_Debug', link: '/reference/lua_c/lua_Debug.md'},
            { text:'lua_Hook', link: '/reference/lua_c/lua_Hook.md'},
            { text:'lua_Integer', link: '/reference/lua_c/lua_Integer.md'},
            { text:'lua_Number', link: '/reference/lua_c/lua_Number.md'},
            { text:'lua_Reader', link: '/reference/lua_c/lua_Reader.md'},
            { text:'lua_State', link: '/reference/lua_c/lua_State.md'},
            { text:'lua_Writer', link: '/reference/lua_c/lua_Writer.md'},
            { text:'luaL_Buffer', link: '/reference/lua_c/luaL_Buffer.md'},
            { text:'luaL_Reg', link: '/reference/lua_c/luaL_Reg.md'},
          ]
        },
        {
          text: '関数',
          collapsed: true,
          items: [
            { text:'lua_atpanic', link: '/reference/lua_c/lua_atpanic.md'},
            { text:'lua_call', link: '/reference/lua_c/lua_call.md'},
            { text:'lua_checkstack', link: '/reference/lua_c/lua_checkstack.md'},
            { text:'lua_close', link: '/reference/lua_c/lua_close.md'},
            { text:'lua_concat', link: '/reference/lua_c/lua_concat.md'},
            { text:'lua_copy', link: '/reference/lua_c/lua_copy.md'},
            { text:'lua_cpcall', link: '/reference/lua_c/lua_cpcall.md'},
            { text:'lua_createtable', link: '/reference/lua_c/lua_createtable.md'},
            { text:'lua_dump', link: '/reference/lua_c/lua_dump.md'},
            { text:'lua_equal', link: '/reference/lua_c/lua_equal.md'},
            { text:'lua_error', link: '/reference/lua_c/lua_error.md'},
            { text:'lua_gc', link: '/reference/lua_c/lua_gc.md'},
            { text:'lua_getallocf', link: '/reference/lua_c/lua_getallocf.md'},
            { text:'lua_getfenv', link: '/reference/lua_c/lua_getfenv.md'},
            { text:'lua_getfield', link: '/reference/lua_c/lua_getfield.md'},
            { text:'lua_getglobal', link: '/reference/lua_c/lua_getglobal.md'},
            { text:'lua_gethook', link: '/reference/lua_c/lua_gethook.md'},
            { text:'lua_gethookcount', link: '/reference/lua_c/lua_gethookcount.md'},
            { text:'lua_gethookmask', link: '/reference/lua_c/lua_gethookmask.md'},
            { text:'lua_getinfo', link: '/reference/lua_c/lua_getinfo.md'},
            { text:'lua_getlocal', link: '/reference/lua_c/lua_getlocal.md'},
            { text:'lua_getmetatable', link: '/reference/lua_c/lua_getmetatable.md'},
            { text:'lua_getstack', link: '/reference/lua_c/lua_getstack.md'},
            { text:'lua_gettable', link: '/reference/lua_c/lua_gettable.md'},
            { text:'lua_gettop', link: '/reference/lua_c/lua_gettop.md'},
            { text:'lua_getupvalue', link: '/reference/lua_c/lua_getupvalue.md'},
            { text:'lua_insert', link: '/reference/lua_c/lua_insert.md'},
            { text:'lua_isboolean', link: '/reference/lua_c/lua_isboolean.md'},
            { text:'lua_iscfunction', link: '/reference/lua_c/lua_iscfunction.md'},
            { text:'lua_isfunction', link: '/reference/lua_c/lua_isfunction.md'},
            { text:'lua_islightuserdata', link: '/reference/lua_c/lua_islightuserdata.md'},
            { text:'lua_isnil', link: '/reference/lua_c/lua_isnil.md'},
            { text:'lua_isnone', link: '/reference/lua_c/lua_isnone.md'},
            { text:'lua_isnoneornil', link: '/reference/lua_c/lua_isnoneornil.md'},
            { text:'lua_isnumber', link: '/reference/lua_c/lua_isnumber.md'},
            { text:'lua_isstring', link: '/reference/lua_c/lua_isstring.md'},
            { text:'lua_istable', link: '/reference/lua_c/lua_istable.md'},
            { text:'lua_isthread', link: '/reference/lua_c/lua_isthread.md'},
            { text:'lua_isuserdata', link: '/reference/lua_c/lua_isuserdata.md'},
            { text:'lua_isyieldable', link: '/reference/lua_c/lua_isyieldable.md'},
            { text:'lua_lessthan', link: '/reference/lua_c/lua_lessthan.md'},
            { text:'lua_load', link: '/reference/lua_c/lua_load.md'},
            { text:'lua_loadx', link: '/reference/lua_c/lua_loadx.md'},
            { text:'lua_newstate', link: '/reference/lua_c/lua_newstate.md'},
            { text:'lua_newtable', link: '/reference/lua_c/lua_newtable.md'},
            { text:'lua_newthread', link: '/reference/lua_c/lua_newthread.md'},
            { text:'lua_newuserdata', link: '/reference/lua_c/lua_newuserdata.md'},
            { text:'lua_next', link: '/reference/lua_c/lua_next.md'},
            { text:'lua_objlen', link: '/reference/lua_c/lua_objlen.md'},
            { text:'lua_pcall', link: '/reference/lua_c/lua_pcall.md'},
            { text:'lua_pop', link: '/reference/lua_c/lua_pop.md'},
            { text:'lua_pushboolean', link: '/reference/lua_c/lua_pushboolean.md'},
            { text:'lua_pushcclosure', link: '/reference/lua_c/lua_pushcclosure.md'},
            { text:'lua_pushcfunction', link: '/reference/lua_c/lua_pushcfunction.md'},
            { text:'lua_pushfstring', link: '/reference/lua_c/lua_pushfstring.md'},
            { text:'lua_pushinteger', link: '/reference/lua_c/lua_pushinteger.md'},
            { text:'lua_pushlightuserdata', link: '/reference/lua_c/lua_pushlightuserdata.md'},
            { text:'lua_pushliteral', link: '/reference/lua_c/lua_pushliteral.md'},
            { text:'lua_pushlstring', link: '/reference/lua_c/lua_pushlstring.md'},
            { text:'lua_pushnil', link: '/reference/lua_c/lua_pushnil.md'},
            { text:'lua_pushnumber', link: '/reference/lua_c/lua_pushnumber.md'},
            { text:'lua_pushstring', link: '/reference/lua_c/lua_pushstring.md'},
            { text:'lua_pushthread', link: '/reference/lua_c/lua_pushthread.md'},
            { text:'lua_pushvalue', link: '/reference/lua_c/lua_pushvalue.md'},
            { text:'lua_pushvfstring', link: '/reference/lua_c/lua_pushvfstring.md'},
            { text:'lua_rawequal', link: '/reference/lua_c/lua_rawequal.md'},
            { text:'lua_rawget', link: '/reference/lua_c/lua_rawget.md'},
            { text:'lua_rawgeti', link: '/reference/lua_c/lua_rawgeti.md'},
            { text:'lua_rawset', link: '/reference/lua_c/lua_rawset.md'},
            { text:'lua_rawseti', link: '/reference/lua_c/lua_rawseti.md'},
            { text:'lua_register', link: '/reference/lua_c/lua_register.md'},
            { text:'lua_remove', link: '/reference/lua_c/lua_remove.md'},
            { text:'lua_replace', link: '/reference/lua_c/lua_replace.md'},
            { text:'lua_resume', link: '/reference/lua_c/lua_resume.md'},
            { text:'lua_setallocf', link: '/reference/lua_c/lua_setallocf.md'},
            { text:'lua_setfenv', link: '/reference/lua_c/lua_setfenv.md'},
            { text:'lua_setfield', link: '/reference/lua_c/lua_setfield.md'},
            { text:'lua_setglobal', link: '/reference/lua_c/lua_setglobal.md'},
            { text:'lua_sethook', link: '/reference/lua_c/lua_sethook.md'},
            { text:'lua_setlocal', link: '/reference/lua_c/lua_setlocal.md'},
            { text:'lua_setmetatable', link: '/reference/lua_c/lua_setmetatable.md'},
            { text:'lua_settable', link: '/reference/lua_c/lua_settable.md'},
            { text:'lua_settop', link: '/reference/lua_c/lua_settop.md'},
            { text:'lua_setupvalue', link: '/reference/lua_c/lua_setupvalue.md'},
            { text:'lua_status', link: '/reference/lua_c/lua_status.md'},
            { text:'lua_toboolean', link: '/reference/lua_c/lua_toboolean.md'},
            { text:'lua_tocfunction', link: '/reference/lua_c/lua_tocfunction.md'},
            { text:'lua_tointeger', link: '/reference/lua_c/lua_tointeger.md'},
            { text:'lua_tointegerx', link: '/reference/lua_c/lua_tointegerx.md'},
            { text:'lua_tolstring', link: '/reference/lua_c/lua_tolstring.md'},
            { text:'lua_tonumber', link: '/reference/lua_c/lua_tonumber.md'},
            { text:'lua_tonumberx', link: '/reference/lua_c/lua_tonumberx.md'},
            { text:'lua_topointer', link: '/reference/lua_c/lua_topointer.md'},
            { text:'lua_tostring', link: '/reference/lua_c/lua_tostring.md'},
            { text:'lua_tothread', link: '/reference/lua_c/lua_tothread.md'},
            { text:'lua_touserdata', link: '/reference/lua_c/lua_touserdata.md'},
            { text:'lua_type', link: '/reference/lua_c/lua_type.md'},
            { text:'lua_typename', link: '/reference/lua_c/lua_typename.md'},
            { text:'lua_upvalueid', link: '/reference/lua_c/lua_upvalueid.md'},
            { text:'lua_upvaluejoin', link: '/reference/lua_c/lua_upvaluejoin.md'},
            { text:'lua_version', link: '/reference/lua_c/lua_version.md'},
            { text:'lua_xmove', link: '/reference/lua_c/lua_xmove.md'},
            { text:'lua_yield', link: '/reference/lua_c/lua_yield.md'},
            { text:'luaL_addchar', link: '/reference/lua_c/luaL_addchar.md'},
            { text:'luaL_addlstring', link: '/reference/lua_c/luaL_addlstring.md'},
            { text:'luaL_addsize', link: '/reference/lua_c/luaL_addsize.md'},
            { text:'luaL_addstring', link: '/reference/lua_c/luaL_addstring.md'},
            { text:'luaL_addvalue', link: '/reference/lua_c/luaL_addvalue.md'},
            { text:'luaL_argcheck', link: '/reference/lua_c/luaL_argcheck.md'},
            { text:'luaL_argerror', link: '/reference/lua_c/luaL_argerror.md'},
            { text:'luaL_buffinit', link: '/reference/lua_c/luaL_buffinit.md'},
            { text:'luaL_callmeta', link: '/reference/lua_c/luaL_callmeta.md'},
            { text:'luaL_checkany', link: '/reference/lua_c/luaL_checkany.md'},
            { text:'luaL_checkint', link: '/reference/lua_c/luaL_checkint.md'},
            { text:'luaL_checkinteger', link: '/reference/lua_c/luaL_checkinteger.md'},
            { text:'luaL_checklong', link: '/reference/lua_c/luaL_checklong.md'},
            { text:'luaL_checklstring', link: '/reference/lua_c/luaL_checklstring.md'},
            { text:'luaL_checknumber', link: '/reference/lua_c/luaL_checknumber.md'},
            { text:'luaL_checkoption', link: '/reference/lua_c/luaL_checkoption.md'},
            { text:'luaL_checkstack', link: '/reference/lua_c/luaL_checkstack.md'},
            { text:'luaL_checkstring', link: '/reference/lua_c/luaL_checkstring.md'},
            { text:'luaL_checktype', link: '/reference/lua_c/luaL_checktype.md'},
            { text:'luaL_checkudata', link: '/reference/lua_c/luaL_checkudata.md'},
            { text:'luaL_dofile', link: '/reference/lua_c/luaL_dofile.md'},
            { text:'luaL_dostring', link: '/reference/lua_c/luaL_dostring.md'},
            { text:'luaL_error', link: '/reference/lua_c/luaL_error.md'},
            { text:'luaL_execresult', link: '/reference/lua_c/luaL_execresult.md'},
            { text:'luaL_fileresult', link: '/reference/lua_c/luaL_fileresult.md'},
            { text:'luaL_getmetafield', link: '/reference/lua_c/luaL_getmetafield.md'},
            { text:'luaL_getmetatable', link: '/reference/lua_c/luaL_getmetatable.md'},
            { text:'luaL_gsub', link: '/reference/lua_c/luaL_gsub.md'},
            { text:'luaL_loadbuffer', link: '/reference/lua_c/luaL_loadbuffer.md'},
            { text:'luaL_loadbufferx', link: '/reference/lua_c/luaL_loadbufferx.md'},
            { text:'luaL_loadfile', link: '/reference/lua_c/luaL_loadfile.md'},
            { text:'luaL_loadfilex', link: '/reference/lua_c/luaL_loadfilex.md'},
            { text:'luaL_loadstring', link: '/reference/lua_c/luaL_loadstring.md'},
            { text:'luaL_newlib', link: '/reference/lua_c/luaL_newlib.md'},
            { text:'luaL_newlibtable', link: '/reference/lua_c/luaL_newlibtable.md'},
            { text:'luaL_newmetatable', link: '/reference/lua_c/luaL_newmetatable.md'},
            { text:'luaL_newstate', link: '/reference/lua_c/luaL_newstate.md'},
            { text:'luaL_openlibs', link: '/reference/lua_c/luaL_openlibs.md'},
            { text:'luaL_optint', link: '/reference/lua_c/luaL_optint.md'},
            { text:'luaL_optinteger', link: '/reference/lua_c/luaL_optinteger.md'},
            { text:'luaL_optlong', link: '/reference/lua_c/luaL_optlong.md'},
            { text:'luaL_optlstring', link: '/reference/lua_c/luaL_optlstring.md'},
            { text:'luaL_optnumber', link: '/reference/lua_c/luaL_optnumber.md'},
            { text:'luaL_optstring', link: '/reference/lua_c/luaL_optstring.md'},
            { text:'luaL_prepbuffer', link: '/reference/lua_c/luaL_prepbuffer.md'},
            { text:'luaL_pushmodule', link: '/reference/lua_c/luaL_pushmodule.md'},
            { text:'luaL_pushresult', link: '/reference/lua_c/luaL_pushresult.md'},
            { text:'luaL_ref', link: '/reference/lua_c/luaL_ref.md'},
            { text:'luaL_register', link: '/reference/lua_c/luaL_register.md'},
            { text:'luaL_setfuncs', link: '/reference/lua_c/luaL_setfuncs.md'},
            { text:'luaL_setmetatable', link: '/reference/lua_c/luaL_setmetatable.md'},
            { text:'luaL_testudata', link: '/reference/lua_c/luaL_testudata.md'},
            { text:'luaL_traceback', link: '/reference/lua_c/luaL_traceback.md'},
            { text:'luaL_typename', link: '/reference/lua_c/luaL_typename.md'},
            { text:'luaL_typerror', link: '/reference/lua_c/luaL_typerror.md'},
            { text:'luaL_unref', link: '/reference/lua_c/luaL_unref.md'},
            { text:'luaL_where', link: '/reference/lua_c/luaL_where.md'},
            { text:'luaJIT_setmode', link: '/reference/lua_c/luaJIT_setmode.md'},
          ]
        },
      ],
      '/resource/cosmopolitan/': [
          {
              text: 'はじめに',
              collapsed: false,
              items: [
                  {text: 'cosmopolitan', link: '/resource/cosmopolitan/'},
                  {text: '概要', link: '/resource/cosmopolitan/top'},
                  {text: 'ツールチェイン', link: '/resource/cosmopolitan/toolchain'},
              ]
          },
          {
              text: 'APE',
              collapsed: false,
              items: [
                  {text: 'APE', link: '/resource/cosmopolitan/ape'},
              ]
          }
      ],
      '/resource/duktape/': [
                {
                    text: 'Duktape',
                    collapsed: false,
                    items: [
                        {text: 'はじめに', link: '/resource/duktape/'},
                    ]
                },
                {
                    text: 'プログラマーズ・ガイド',
                    collapsed: true,
                    items: [
                        {text: 'はじめに', link: '/resource/duktape/guide/'},
                        {text: 'イントロダクション', link: '/resource/duktape/guide/introduction.md'},
                        {text: 'スタートアップ', link: '/resource/duktape/guide/getting_started.md'},
                        {text: 'プログラミングモデル', link: '/resource/duktape/guide/programming_model.md'},
                        {text: 'スタックタイプ', link: '/resource/duktape/guide/stack_types.md'},
                        {text: 'C言語の型', link: '/resource/duktape/guide/api_c_types.md'},
                        {text: '型のアルゴリズム', link: '/resource/duktape/guide/type_algorithms.md'},
                        {text: 'ビルトイン', link: '/resource/duktape/guide/duktape_built_ins.md'},
                        {text: 'ポストES5の特徴', link: '/resource/duktape/guide/post_es5_features.md'},
                        {text: 'カスタム動作', link: '/resource/duktape/guide/custom_behavior.md'},
                        {text: 'カスタムJSONフォーマット', link: '/resource/duktape/guide/custom_json_formats.md'},
                        {text: 'カスタムディレクティブ', link: '/resource/duktape/guide/custom_directives.md'},
                        {text: 'バッファー', link: '/resource/duktape/guide/buffer_objects.md'},
                        {text: 'エラー', link: '/resource/duktape/guide/error_objects.md'},
                        {text: '関数', link: '/resource/duktape/guide/function_objects.md'},
                        {text: '日付と時刻', link: '/resource/duktape/guide/date_and_time.md'},
                        {text: '乱数', link: '/resource/duktape/guide/random_numbers.md'},
                        {text: 'デバッガー', link: '/resource/duktape/guide/debugger.md'},
                        {text: 'モジュール', link: '/resource/duktape/guide/modules.md'},
                        {text: 'ログ管理', link: '/resource/duktape/guide/logging.md'},
                        {text: '終了処理', link: '/resource/duktape/guide/finalization.md'},
                        {text: 'コルーチン', link: '/resource/duktape/guide/coroutines.md'},
                        {text: '仮想プロパティ', link: '/resource/duktape/guide/virtual_properties.md'},
                        {text: 'シンボル', link: '/resource/duktape/guide/symbols.md'},
                        {text: 'バイトコード', link: '/resource/duktape/guide/bytecode_dump_load.md'},
                        {text: 'スレッディング', link: '/resource/duktape/guide/threading.md'},
                        {text: 'サンドボックス', link: '/resource/duktape/guide/sandboxing.md'},
                        {text: 'パフォーマンス', link: '/resource/duktape/guide/performance.md'},
                        {text: 'メモリ使用量', link: '/resource/duktape/guide/memory_usage.md'},
                        {text: 'コンパイル方法', link: '/resource/duktape/guide/compiling.md'},
                        {text: '移植性', link: '/resource/duktape/guide/portability.md'},
                        {text: '互換性', link: '/resource/duktape/guide/compatibility.md'},
                        {text: 'バージョン管理', link: '/resource/duktape/guide/versioning.md'},
                        {text: '制限事項', link: '/resource/duktape/guide/limitations.md'},
                        {text: 'Luaとの比較', link: '/resource/duktape/guide/comparison_to_lua.md'},
                    ]
                },
                {
                    text: 'APIリファレンス',
                    collapsed: true,
                    items: [
                        {text: 'はじめに', link: '/resource/duktape/api/'},
                        {text: 'duk_alloc', link: '/resource/duktape/api/duk_alloc.md'},
                        {text: 'duk_alloc_raw', link: '/resource/duktape/api/duk_alloc_raw.md'},
                        {text: 'duk_base64_decode', link: '/resource/duktape/api/duk_base64_decode.md'},
                        {text: 'duk_base64_encode', link: '/resource/duktape/api/duk_base64_encode.md'},
                        {text: 'duk_call', link: '/resource/duktape/api/duk_call.md'},
                        {text: 'duk_call_method', link: '/resource/duktape/api/duk_call_method.md'},
                        {text: 'duk_call_prop', link: '/resource/duktape/api/duk_call_prop.md'},
                        {text: 'duk_char_code_at', link: '/resource/duktape/api/duk_char_code_at.md'},
                        {text: 'duk_check_stack', link: '/resource/duktape/api/duk_check_stack.md'},
                        {text: 'duk_check_stack_top', link: '/resource/duktape/api/duk_check_stack_top.md'},
                        {text: 'duk_check_type', link: '/resource/duktape/api/duk_check_type.md'},
                        {text: 'duk_check_type_mask', link: '/resource/duktape/api/duk_check_type_mask.md'},
                        {text: 'duk_compact', link: '/resource/duktape/api/duk_compact.md'},
                        {text: 'duk_compile', link: '/resource/duktape/api/duk_compile.md'},
                        {text: 'duk_compile_lstring', link: '/resource/duktape/api/duk_compile_lstring.md'},
                        {text: 'duk_compile_lstring_filename', link: '/resource/duktape/api/duk_compile_lstring_filename.md'},
                        {text: 'duk_compile_string', link: '/resource/duktape/api/duk_compile_string.md'},
                        {text: 'duk_compile_string_filename', link: '/resource/duktape/api/duk_compile_string_filename.md'},
                        {text: 'duk_concat', link: '/resource/duktape/api/duk_concat.md'},
                        {text: 'duk_copy', link: '/resource/duktape/api/duk_copy.md'},
                        {text: 'duk_create_heap', link: '/resource/duktape/api/duk_create_heap.md'},
                        {text: 'duk_create_heap_default', link: '/resource/duktape/api/duk_create_heap_default.md'},
                        {text: 'duk_decode_string', link: '/resource/duktape/api/duk_decode_string.md'},
                        {text: 'duk_del_prop', link: '/resource/duktape/api/duk_del_prop.md'},
                        {text: 'duk_del_prop_index', link: '/resource/duktape/api/duk_del_prop_index.md'},
                        {text: 'duk_del_prop_string', link: '/resource/duktape/api/duk_del_prop_string.md'},
                        {text: 'duk_destroy_heap', link: '/resource/duktape/api/duk_destroy_heap.md'},
                        {text: 'duk_dup', link: '/resource/duktape/api/duk_dup.md'},
                        {text: 'duk_dup_top', link: '/resource/duktape/api/duk_dup_top.md'},
                        {text: 'duk_enum', link: '/resource/duktape/api/duk_enum.md'},
                        {text: 'duk_equals', link: '/resource/duktape/api/duk_equals.md'},
                        {text: 'duk_error', link: '/resource/duktape/api/duk_error.md'},
                        {text: 'duk_eval', link: '/resource/duktape/api/duk_eval.md'},
                        {text: 'duk_eval_lstring', link: '/resource/duktape/api/duk_eval_lstring.md'},
                        {text: 'duk_eval_lstring_noresult', link: '/resource/duktape/api/duk_eval_lstring_noresult.md'},
                        {text: 'duk_eval_noresult', link: '/resource/duktape/api/duk_eval_noresult.md'},
                        {text: 'duk_eval_string', link: '/resource/duktape/api/duk_eval_string.md'},
                        {text: 'duk_eval_string_noresult', link: '/resource/duktape/api/duk_eval_string_noresult.md'},
                        {text: 'duk_fatal', link: '/resource/duktape/api/duk_fatal.md'},
                        {text: 'duk_free', link: '/resource/duktape/api/duk_free.md'},
                        {text: 'duk_free_raw', link: '/resource/duktape/api/duk_free_raw.md'},
                        {text: 'duk_gc', link: '/resource/duktape/api/duk_gc.md'},
                        {text: 'duk_get_boolean', link: '/resource/duktape/api/duk_get_boolean.md'},
                        {text: 'duk_get_buffer', link: '/resource/duktape/api/duk_get_buffer.md'},
                        {text: 'duk_get_c_function', link: '/resource/duktape/api/duk_get_c_function.md'},
                        {text: 'duk_get_context', link: '/resource/duktape/api/duk_get_context.md'},
                        {text: 'duk_get_current_magic', link: '/resource/duktape/api/duk_get_current_magic.md'},
                        {text: 'duk_get_finalizer', link: '/resource/duktape/api/duk_get_finalizer.md'},
                        {text: 'duk_get_global_string', link: '/resource/duktape/api/duk_get_global_string.md'},
                        {text: 'duk_get_int', link: '/resource/duktape/api/duk_get_int.md'},
                        {text: 'duk_get_length', link: '/resource/duktape/api/duk_get_length.md'},
                        {text: 'duk_get_lstring', link: '/resource/duktape/api/duk_get_lstring.md'},
                        {text: 'duk_get_magic', link: '/resource/duktape/api/duk_get_magic.md'},
                        {text: 'duk_get_memory_functions', link: '/resource/duktape/api/duk_get_memory_functions.md'},
                        {text: 'duk_get_number', link: '/resource/duktape/api/duk_get_number.md'},
                        {text: 'duk_get_pointer', link: '/resource/duktape/api/duk_get_pointer.md'},
                        {text: 'duk_get_prop', link: '/resource/duktape/api/duk_get_prop.md'},
                        {text: 'duk_get_prop_index', link: '/resource/duktape/api/duk_get_prop_index.md'},
                        {text: 'duk_get_prop_string', link: '/resource/duktape/api/duk_get_prop_string.md'},
                        {text: 'duk_get_prototype', link: '/resource/duktape/api/duk_get_prototype.md'},
                        {text: 'duk_get_string', link: '/resource/duktape/api/duk_get_string.md'},
                        {text: 'duk_get_top', link: '/resource/duktape/api/duk_get_top.md'},
                        {text: 'duk_get_top_index', link: '/resource/duktape/api/duk_get_top_index.md'},
                        {text: 'duk_get_type', link: '/resource/duktape/api/duk_get_type.md'},
                        {text: 'duk_get_type_mask', link: '/resource/duktape/api/duk_get_type_mask.md'},
                        {text: 'duk_get_uint', link: '/resource/duktape/api/duk_get_uint.md'},
                        {text: 'duk_has_prop', link: '/resource/duktape/api/duk_has_prop.md'},
                        {text: 'duk_has_prop_index', link: '/resource/duktape/api/duk_has_prop_index.md'},
                        {text: 'duk_has_prop_string', link: '/resource/duktape/api/duk_has_prop_string.md'},
                        {text: 'duk_hex_decode', link: '/resource/duktape/api/duk_hex_decode.md'},
                        {text: 'duk_hex_encode', link: '/resource/duktape/api/duk_hex_encode.md'},
                        {text: 'duk_insert', link: '/resource/duktape/api/duk_insert.md'},
                        {text: 'duk_is_array', link: '/resource/duktape/api/duk_is_array.md'},
                        {text: 'duk_is_boolean', link: '/resource/duktape/api/duk_is_boolean.md'},
                        {text: 'duk_is_bound_function', link: '/resource/duktape/api/duk_is_bound_function.md'},
                        {text: 'duk_is_buffer', link: '/resource/duktape/api/duk_is_buffer.md'},
                        {text: 'duk_is_c_function', link: '/resource/duktape/api/duk_is_c_function.md'},
                        {text: 'duk_is_callable', link: '/resource/duktape/api/duk_is_callable.md'},
                        {text: 'duk_is_constructor_call', link: '/resource/duktape/api/duk_is_constructor_call.md'},
                        {text: 'duk_is_dynamic_buffer', link: '/resource/duktape/api/duk_is_dynamic_buffer.md'},
                        {text: 'duk_is_ecmascript_function', link: '/resource/duktape/api/duk_is_ecmascript_function.md'},
                        {text: 'duk_is_fixed_buffer', link: '/resource/duktape/api/duk_is_fixed_buffer.md'},
                        {text: 'duk_is_function', link: '/resource/duktape/api/duk_is_function.md'},
                        {text: 'duk_is_lightfunc', link: '/resource/duktape/api/duk_is_lightfunc.md'},
                        {text: 'duk_is_nan', link: '/resource/duktape/api/duk_is_nan.md'},
                        {text: 'duk_is_null', link: '/resource/duktape/api/duk_is_null.md'},
                        {text: 'duk_is_null_or_undefined', link: '/resource/duktape/api/duk_is_null_or_undefined.md'},
                        {text: 'duk_is_number', link: '/resource/duktape/api/duk_is_number.md'},
                        {text: 'duk_is_object', link: '/resource/duktape/api/duk_is_object.md'},
                        {text: 'duk_is_object_coercible', link: '/resource/duktape/api/duk_is_object_coercible.md'},
                        {text: 'duk_is_pointer', link: '/resource/duktape/api/duk_is_pointer.md'},
                        {text: 'duk_is_primitive', link: '/resource/duktape/api/duk_is_primitive.md'},
                        {text: 'duk_is_strict_call', link: '/resource/duktape/api/duk_is_strict_call.md'},
                        {text: 'duk_is_string', link: '/resource/duktape/api/duk_is_string.md'},
                        {text: 'duk_is_thread', link: '/resource/duktape/api/duk_is_thread.md'},
                        {text: 'duk_is_undefined', link: '/resource/duktape/api/duk_is_undefined.md'},
                        {text: 'duk_is_valid_index', link: '/resource/duktape/api/duk_is_valid_index.md'},
                        {text: 'duk_join', link: '/resource/duktape/api/duk_join.md'},
                        {text: 'duk_json_decode', link: '/resource/duktape/api/duk_json_decode.md'},
                        {text: 'duk_json_encode', link: '/resource/duktape/api/duk_json_encode.md'},
                        {text: 'duk_map_string', link: '/resource/duktape/api/duk_map_string.md'},
                        {text: 'duk_new', link: '/resource/duktape/api/duk_new.md'},
                        {text: 'duk_next', link: '/resource/duktape/api/duk_next.md'},
                        {text: 'duk_normalize_index', link: '/resource/duktape/api/duk_normalize_index.md'},
                        {text: 'duk_pcall', link: '/resource/duktape/api/duk_pcall.md'},
                        {text: 'duk_pcall_method', link: '/resource/duktape/api/duk_pcall_method.md'},
                        {text: 'duk_pcall_prop', link: '/resource/duktape/api/duk_pcall_prop.md'},
                        {text: 'duk_pcompile', link: '/resource/duktape/api/duk_pcompile.md'},
                        {text: 'duk_pcompile_lstring', link: '/resource/duktape/api/duk_pcompile_lstring.md'},
                        {text: 'duk_pcompile_lstring_filename', link: '/resource/duktape/api/duk_pcompile_lstring_filename.md'},
                        {text: 'duk_pcompile_string', link: '/resource/duktape/api/duk_pcompile_string.md'},
                        {text: 'duk_pcompile_string_filename', link: '/resource/duktape/api/duk_pcompile_string_filename.md'},
                        {text: 'duk_peval', link: '/resource/duktape/api/duk_peval.md'},
                        {text: 'duk_peval_lstring', link: '/resource/duktape/api/duk_peval_lstring.md'},
                        {text: 'duk_peval_lstring_noresult', link: '/resource/duktape/api/duk_peval_lstring_noresult.md'},
                        {text: 'duk_peval_noresult', link: '/resource/duktape/api/duk_peval_noresult.md'},
                        {text: 'duk_peval_string', link: '/resource/duktape/api/duk_peval_string.md'},
                        {text: 'duk_peval_string_noresult', link: '/resource/duktape/api/duk_peval_string_noresult.md'},
                        {text: 'duk_pop', link: '/resource/duktape/api/duk_pop.md'},
                        {text: 'duk_pop_2', link: '/resource/duktape/api/duk_pop_2.md'},
                        {text: 'duk_pop_3', link: '/resource/duktape/api/duk_pop_3.md'},
                        {text: 'duk_pop_n', link: '/resource/duktape/api/duk_pop_n.md'},
                        {text: 'duk_push_array', link: '/resource/duktape/api/duk_push_array.md'},
                        {text: 'duk_push_boolean', link: '/resource/duktape/api/duk_push_boolean.md'},
                        {text: 'duk_push_buffer', link: '/resource/duktape/api/duk_push_buffer.md'},
                        {text: 'duk_push_c_function', link: '/resource/duktape/api/duk_push_c_function.md'},
                        {text: 'duk_push_c_lightfunc', link: '/resource/duktape/api/duk_push_c_lightfunc.md'},
                        {text: 'duk_push_context_dump', link: '/resource/duktape/api/duk_push_context_dump.md'},
                        {text: 'duk_push_current_function', link: '/resource/duktape/api/duk_push_current_function.md'},
                        {text: 'duk_push_current_thread', link: '/resource/duktape/api/duk_push_current_thread.md'},
                        {text: 'duk_push_dynamic_buffer', link: '/resource/duktape/api/duk_push_dynamic_buffer.md'},
                        {text: 'duk_push_error_object', link: '/resource/duktape/api/duk_push_error_object.md'},
                        {text: 'duk_push_false', link: '/resource/duktape/api/duk_push_false.md'},
                        {text: 'duk_push_fixed_buffer', link: '/resource/duktape/api/duk_push_fixed_buffer.md'},
                        {text: 'duk_push_global_object', link: '/resource/duktape/api/duk_push_global_object.md'},
                        {text: 'duk_push_global_stash', link: '/resource/duktape/api/duk_push_global_stash.md'},
                        {text: 'duk_push_heap_stash', link: '/resource/duktape/api/duk_push_heap_stash.md'},
                        {text: 'duk_push_int', link: '/resource/duktape/api/duk_push_int.md'},
                        {text: 'duk_push_lstring', link: '/resource/duktape/api/duk_push_lstring.md'},
                        {text: 'duk_push_nan', link: '/resource/duktape/api/duk_push_nan.md'},
                        {text: 'duk_push_null', link: '/resource/duktape/api/duk_push_null.md'},
                        {text: 'duk_push_number', link: '/resource/duktape/api/duk_push_number.md'},
                        {text: 'duk_push_object', link: '/resource/duktape/api/duk_push_object.md'},
                        {text: 'duk_push_pointer', link: '/resource/duktape/api/duk_push_pointer.md'},
                        {text: 'duk_push_sprintf', link: '/resource/duktape/api/duk_push_sprintf.md'},
                        {text: 'duk_push_string', link: '/resource/duktape/api/duk_push_string.md'},
                        {text: 'duk_push_this', link: '/resource/duktape/api/duk_push_this.md'},
                        {text: 'duk_push_thread', link: '/resource/duktape/api/duk_push_thread.md'},
                        {text: 'duk_push_thread_new_globalenv', link: '/resource/duktape/api/duk_push_thread_new_globalenv.md'},
                        {text: 'duk_push_thread_stash', link: '/resource/duktape/api/duk_push_thread_stash.md'},
                        {text: 'duk_push_true', link: '/resource/duktape/api/duk_push_true.md'},
                        {text: 'duk_push_uint', link: '/resource/duktape/api/duk_push_uint.md'},
                        {text: 'duk_push_undefined', link: '/resource/duktape/api/duk_push_undefined.md'},
                        {text: 'duk_push_vsprintf', link: '/resource/duktape/api/duk_push_vsprintf.md'},
                        {text: 'duk_put_function_list', link: '/resource/duktape/api/duk_put_function_list.md'},
                        {text: 'duk_put_global_string', link: '/resource/duktape/api/duk_put_global_string.md'},
                        {text: 'duk_put_number_list', link: '/resource/duktape/api/duk_put_number_list.md'},
                        {text: 'duk_put_prop', link: '/resource/duktape/api/duk_put_prop.md'},
                        {text: 'duk_put_prop_index', link: '/resource/duktape/api/duk_put_prop_index.md'},
                        {text: 'duk_put_prop_string', link: '/resource/duktape/api/duk_put_prop_string.md'},
                        {text: 'duk_realloc', link: '/resource/duktape/api/duk_realloc.md'},
                        {text: 'duk_realloc_raw', link: '/resource/duktape/api/duk_realloc_raw.md'},
                        {text: 'duk_remove', link: '/resource/duktape/api/duk_remove.md'},
                        {text: 'duk_replace', link: '/resource/duktape/api/duk_replace.md'},
                        {text: 'duk_require_boolean', link: '/resource/duktape/api/duk_require_boolean.md'},
                        {text: 'duk_require_buffer', link: '/resource/duktape/api/duk_require_buffer.md'},
                        {text: 'duk_require_c_function', link: '/resource/duktape/api/duk_require_c_function.md'},
                        {text: 'duk_require_context', link: '/resource/duktape/api/duk_require_context.md'},
                        {text: 'duk_require_int', link: '/resource/duktape/api/duk_require_int.md'},
                        {text: 'duk_require_lstring', link: '/resource/duktape/api/duk_require_lstring.md'},
                        {text: 'duk_require_normalize_index', link: '/resource/duktape/api/duk_require_normalize_index.md'},
                        {text: 'duk_require_null', link: '/resource/duktape/api/duk_require_null.md'},
                        {text: 'duk_require_number', link: '/resource/duktape/api/duk_require_number.md'},
                        {text: 'duk_require_object_coercible', link: '/resource/duktape/api/duk_require_object_coercible.md'},
                        {text: 'duk_require_pointer', link: '/resource/duktape/api/duk_require_pointer.md'},
                        {text: 'duk_require_stack', link: '/resource/duktape/api/duk_require_stack.md'},
                        {text: 'duk_require_stack_top', link: '/resource/duktape/api/duk_require_stack_top.md'},
                        {text: 'duk_require_string', link: '/resource/duktape/api/duk_require_string.md'},
                        {text: 'duk_require_top_index', link: '/resource/duktape/api/duk_require_top_index.md'},
                        {text: 'duk_require_type_mask', link: '/resource/duktape/api/duk_require_type_mask.md'},
                        {text: 'duk_require_uint', link: '/resource/duktape/api/duk_require_uint.md'},
                        {text: 'duk_require_undefined', link: '/resource/duktape/api/duk_require_undefined.md'},
                        {text: 'duk_require_valid_index', link: '/resource/duktape/api/duk_require_valid_index.md'},
                        {text: 'duk_resize_buffer', link: '/resource/duktape/api/duk_resize_buffer.md'},
                        {text: 'duk_safe_call', link: '/resource/duktape/api/duk_safe_call.md'},
                        {text: 'duk_safe_to_lstring', link: '/resource/duktape/api/duk_safe_to_lstring.md'},
                        {text: 'duk_safe_to_string', link: '/resource/duktape/api/duk_safe_to_string.md'},
                        {text: 'duk_set_finalizer', link: '/resource/duktape/api/duk_set_finalizer.md'},
                        {text: 'duk_set_global_object', link: '/resource/duktape/api/duk_set_global_object.md'},
                        {text: 'duk_set_magic', link: '/resource/duktape/api/duk_set_magic.md'},
                        {text: 'duk_set_prototype', link: '/resource/duktape/api/duk_set_prototype.md'},
                        {text: 'duk_set_top', link: '/resource/duktape/api/duk_set_top.md'},
                        {text: 'duk_strict_equals', link: '/resource/duktape/api/duk_strict_equals.md'},
                        {text: 'duk_substring', link: '/resource/duktape/api/duk_substring.md'},
                        {text: 'duk_swap', link: '/resource/duktape/api/duk_swap.md'},
                        {text: 'duk_swap_top', link: '/resource/duktape/api/duk_swap_top.md'},
                        {text: 'duk_throw', link: '/resource/duktape/api/duk_throw.md'},
                        {text: 'duk_to_boolean', link: '/resource/duktape/api/duk_to_boolean.md'},
                        {text: 'duk_to_buffer', link: '/resource/duktape/api/duk_to_buffer.md'},
                        {text: 'duk_to_dynamic_buffer', link: '/resource/duktape/api/duk_to_dynamic_buffer.md'},
                        {text: 'duk_to_fixed_buffer', link: '/resource/duktape/api/duk_to_fixed_buffer.md'},
                        {text: 'duk_to_int', link: '/resource/duktape/api/duk_to_int.md'},
                        {text: 'duk_to_int32', link: '/resource/duktape/api/duk_to_int32.md'},
                        {text: 'duk_to_lstring', link: '/resource/duktape/api/duk_to_lstring.md'},
                        {text: 'duk_to_null', link: '/resource/duktape/api/duk_to_null.md'},
                        {text: 'duk_to_number', link: '/resource/duktape/api/duk_to_number.md'},
                        {text: 'duk_to_object', link: '/resource/duktape/api/duk_to_object.md'},
                        {text: 'duk_to_pointer', link: '/resource/duktape/api/duk_to_pointer.md'},
                        {text: 'duk_to_primitive', link: '/resource/duktape/api/duk_to_primitive.md'},
                        {text: 'duk_to_string', link: '/resource/duktape/api/duk_to_string.md'},
                        {text: 'duk_to_uint', link: '/resource/duktape/api/duk_to_uint.md'},
                        {text: 'duk_to_uint16', link: '/resource/duktape/api/duk_to_uint16.md'},
                        {text: 'duk_to_uint32', link: '/resource/duktape/api/duk_to_uint32.md'},
                        {text: 'duk_to_undefined', link: '/resource/duktape/api/duk_to_undefined.md'},
                        {text: 'duk_trim', link: '/resource/duktape/api/duk_trim.md'},
                        {text: 'duk_xcopy_top', link: '/resource/duktape/api/duk_xcopy_top.md'},
                        {text: 'duk_xmove_top', link: '/resource/duktape/api/duk_xmove_top.md'},
                        {text: 'duk_def_prop', link: '/resource/duktape/api/duk_def_prop.md'},
                        {text: 'duk_error_va', link: '/resource/duktape/api/duk_error_va.md'},
                        {text: 'duk_get_error_code', link: '/resource/duktape/api/duk_get_error_code.md'},
                        {text: 'duk_get_heapptr', link: '/resource/duktape/api/duk_get_heapptr.md'},
                        {text: 'duk_is_error', link: '/resource/duktape/api/duk_is_error.md'},
                        {text: 'duk_push_error_object_va', link: '/resource/duktape/api/duk_push_error_object_va.md'},
                        {text: 'duk_push_heapptr', link: '/resource/duktape/api/duk_push_heapptr.md'},
                        {text: 'duk_require_heapptr', link: '/resource/duktape/api/duk_require_heapptr.md'},
                        {text: 'duk_debugger_attach', link: '/resource/duktape/api/duk_debugger_attach.md'},
                        {text: 'duk_debugger_cooperate', link: '/resource/duktape/api/duk_debugger_cooperate.md'},
                        {text: 'duk_debugger_detach', link: '/resource/duktape/api/duk_debugger_detach.md'},
                        {text: 'duk_config_buffer', link: '/resource/duktape/api/duk_config_buffer.md'},
                        {text: 'duk_dump_function', link: '/resource/duktape/api/duk_dump_function.md'},
                        {text: 'duk_get_buffer_data', link: '/resource/duktape/api/duk_get_buffer_data.md'},
                        {text: 'duk_instanceof', link: '/resource/duktape/api/duk_instanceof.md'},
                        {text: 'duk_load_function', link: '/resource/duktape/api/duk_load_function.md'},
                        {text: 'duk_pnew', link: '/resource/duktape/api/duk_pnew.md'},
                        {text: 'duk_push_buffer_object', link: '/resource/duktape/api/duk_push_buffer_object.md'},
                        {text: 'duk_push_external_buffer', link: '/resource/duktape/api/duk_push_external_buffer.md'},
                        {text: 'duk_require_buffer_data', link: '/resource/duktape/api/duk_require_buffer_data.md'},
                        {text: 'duk_steal_buffer', link: '/resource/duktape/api/duk_steal_buffer.md'},
                        {text: 'duk_is_eval_error', link: '/resource/duktape/api/duk_is_eval_error.md'},
                        {text: 'duk_is_range_error', link: '/resource/duktape/api/duk_is_range_error.md'},
                        {text: 'duk_is_reference_error', link: '/resource/duktape/api/duk_is_reference_error.md'},
                        {text: 'duk_is_syntax_error', link: '/resource/duktape/api/duk_is_syntax_error.md'},
                        {text: 'duk_is_type_error', link: '/resource/duktape/api/duk_is_type_error.md'},
                        {text: 'duk_is_uri_error', link: '/resource/duktape/api/duk_is_uri_error.md'},
                        {text: 'duk_require_callable', link: '/resource/duktape/api/duk_require_callable.md'},
                        {text: 'duk_require_function', link: '/resource/duktape/api/duk_require_function.md'},
                        {text: 'duk_debugger_notify', link: '/resource/duktape/api/duk_debugger_notify.md'},
                        {text: 'duk_debugger_pause', link: '/resource/duktape/api/duk_debugger_pause.md'},
                        {text: 'duk_resume', link: '/resource/duktape/api/duk_resume.md'},
                        {text: 'duk_suspend', link: '/resource/duktape/api/duk_suspend.md'},
                        {text: 'duk_buffer_to_string', link: '/resource/duktape/api/duk_buffer_to_string.md'},
                        {text: 'duk_components_to_time', link: '/resource/duktape/api/duk_components_to_time.md'},
                        {text: 'duk_del_prop_lstring', link: '/resource/duktape/api/duk_del_prop_lstring.md'},
                        {text: 'duk_eval_error', link: '/resource/duktape/api/duk_eval_error.md'},
                        {text: 'duk_eval_error_va', link: '/resource/duktape/api/duk_eval_error_va.md'},
                        {text: 'duk_generic_error', link: '/resource/duktape/api/duk_generic_error.md'},
                        {text: 'duk_generic_error_va', link: '/resource/duktape/api/duk_generic_error_va.md'},
                        {text: 'duk_get_global_lstring', link: '/resource/duktape/api/duk_get_global_lstring.md'},
                        {text: 'duk_get_now', link: '/resource/duktape/api/duk_get_now.md'},
                        {text: 'duk_get_prop_desc', link: '/resource/duktape/api/duk_get_prop_desc.md'},
                        {text: 'duk_get_prop_lstring', link: '/resource/duktape/api/duk_get_prop_lstring.md'},
                        {text: 'duk_has_prop_lstring', link: '/resource/duktape/api/duk_has_prop_lstring.md'},
                        {text: 'duk_inspect_callstack_entry', link: '/resource/duktape/api/duk_inspect_callstack_entry.md'},
                        {text: 'duk_inspect_value', link: '/resource/duktape/api/duk_inspect_value.md'},
                        {text: 'duk_is_buffer_data', link: '/resource/duktape/api/duk_is_buffer_data.md'},
                        {text: 'duk_is_symbol', link: '/resource/duktape/api/duk_is_symbol.md'},
                        {text: 'duk_push_bare_object', link: '/resource/duktape/api/duk_push_bare_object.md'},
                        {text: 'duk_put_global_lstring', link: '/resource/duktape/api/duk_put_global_lstring.md'},
                        {text: 'duk_put_prop_lstring', link: '/resource/duktape/api/duk_put_prop_lstring.md'},
                        {text: 'duk_range_error', link: '/resource/duktape/api/duk_range_error.md'},
                        {text: 'duk_range_error_va', link: '/resource/duktape/api/duk_range_error_va.md'},
                        {text: 'duk_reference_error', link: '/resource/duktape/api/duk_reference_error.md'},
                        {text: 'duk_reference_error_va', link: '/resource/duktape/api/duk_reference_error_va.md'},
                        {text: 'duk_samevalue', link: '/resource/duktape/api/duk_samevalue.md'},
                        {text: 'duk_set_length', link: '/resource/duktape/api/duk_set_length.md'},
                        {text: 'duk_syntax_error', link: '/resource/duktape/api/duk_syntax_error.md'},
                        {text: 'duk_syntax_error_va', link: '/resource/duktape/api/duk_syntax_error_va.md'},
                        {text: 'duk_time_to_components', link: '/resource/duktape/api/duk_time_to_components.md'},
                        {text: 'duk_type_error', link: '/resource/duktape/api/duk_type_error.md'},
                        {text: 'duk_type_error_va', link: '/resource/duktape/api/duk_type_error_va.md'},
                        {text: 'duk_uri_error', link: '/resource/duktape/api/duk_uri_error.md'},
                        {text: 'duk_uri_error_va', link: '/resource/duktape/api/duk_uri_error_va.md'},
                        {text: 'duk_get_boolean_default', link: '/resource/duktape/api/duk_get_boolean_default.md'},
                        {text: 'duk_get_buffer_data_default', link: '/resource/duktape/api/duk_get_buffer_data_default.md'},
                        {text: 'duk_get_buffer_default', link: '/resource/duktape/api/duk_get_buffer_default.md'},
                        {text: 'duk_get_c_function_default', link: '/resource/duktape/api/duk_get_c_function_default.md'},
                        {text: 'duk_get_context_default', link: '/resource/duktape/api/duk_get_context_default.md'},
                        {text: 'duk_get_heapptr_default', link: '/resource/duktape/api/duk_get_heapptr_default.md'},
                        {text: 'duk_get_int_default', link: '/resource/duktape/api/duk_get_int_default.md'},
                        {text: 'duk_get_lstring_default', link: '/resource/duktape/api/duk_get_lstring_default.md'},
                        {text: 'duk_get_number_default', link: '/resource/duktape/api/duk_get_number_default.md'},
                        {text: 'duk_get_pointer_default', link: '/resource/duktape/api/duk_get_pointer_default.md'},
                        {text: 'duk_get_string_default', link: '/resource/duktape/api/duk_get_string_default.md'},
                        {text: 'duk_get_uint_default', link: '/resource/duktape/api/duk_get_uint_default.md'},
                        {text: 'duk_opt_boolean', link: '/resource/duktape/api/duk_opt_boolean.md'},
                        {text: 'duk_opt_buffer', link: '/resource/duktape/api/duk_opt_buffer.md'},
                        {text: 'duk_opt_buffer_data', link: '/resource/duktape/api/duk_opt_buffer_data.md'},
                        {text: 'duk_opt_c_function', link: '/resource/duktape/api/duk_opt_c_function.md'},
                        {text: 'duk_opt_context', link: '/resource/duktape/api/duk_opt_context.md'},
                        {text: 'duk_opt_heapptr', link: '/resource/duktape/api/duk_opt_heapptr.md'},
                        {text: 'duk_opt_int', link: '/resource/duktape/api/duk_opt_int.md'},
                        {text: 'duk_opt_lstring', link: '/resource/duktape/api/duk_opt_lstring.md'},
                        {text: 'duk_opt_number', link: '/resource/duktape/api/duk_opt_number.md'},
                        {text: 'duk_opt_pointer', link: '/resource/duktape/api/duk_opt_pointer.md'},
                        {text: 'duk_opt_string', link: '/resource/duktape/api/duk_opt_string.md'},
                        {text: 'duk_opt_uint', link: '/resource/duktape/api/duk_opt_uint.md'},
                        {text: 'duk_del_prop_heapptr', link: '/resource/duktape/api/duk_del_prop_heapptr.md'},
                        {text: 'duk_freeze', link: '/resource/duktape/api/duk_freeze.md'},
                        {text: 'duk_get_prop_heapptr', link: '/resource/duktape/api/duk_get_prop_heapptr.md'},
                        {text: 'duk_has_prop_heapptr', link: '/resource/duktape/api/duk_has_prop_heapptr.md'},
                        {text: 'duk_is_constructable', link: '/resource/duktape/api/duk_is_constructable.md'},
                        {text: 'duk_push_proxy', link: '/resource/duktape/api/duk_push_proxy.md'},
                        {text: 'duk_put_prop_heapptr', link: '/resource/duktape/api/duk_put_prop_heapptr.md'},
                        {text: 'duk_require_object', link: '/resource/duktape/api/duk_require_object.md'},
                        {text: 'duk_seal', link: '/resource/duktape/api/duk_seal.md'},
                        {text: 'duk_del_prop_literal', link: '/resource/duktape/api/duk_del_prop_literal.md'},
                        {text: 'duk_get_global_heapptr', link: '/resource/duktape/api/duk_get_global_heapptr.md'},
                        {text: 'duk_get_global_literal', link: '/resource/duktape/api/duk_get_global_literal.md'},
                        {text: 'duk_get_prop_literal', link: '/resource/duktape/api/duk_get_prop_literal.md'},
                        {text: 'duk_has_prop_literal', link: '/resource/duktape/api/duk_has_prop_literal.md'},
                        {text: 'duk_push_literal', link: '/resource/duktape/api/duk_push_literal.md'},
                        {text: 'duk_push_new_target', link: '/resource/duktape/api/duk_push_new_target.md'},
                        {text: 'duk_put_global_heapptr', link: '/resource/duktape/api/duk_put_global_heapptr.md'},
                        {text: 'duk_put_global_literal', link: '/resource/duktape/api/duk_put_global_literal.md'},
                        {text: 'duk_put_prop_literal', link: '/resource/duktape/api/duk_put_prop_literal.md'},
                        {text: 'duk_random', link: '/resource/duktape/api/duk_random.md'},
                        {text: 'duk_push_bare_array', link: '/resource/duktape/api/duk_push_bare_array.md'},
                        {text: 'duk_require_constructable', link: '/resource/duktape/api/duk_require_constructable.md'},
                        {text: 'duk_require_constructor_call', link: '/resource/duktape/api/duk_require_constructor_call.md'},
                        {text: 'duk_safe_to_stacktrace', link: '/resource/duktape/api/duk_safe_to_stacktrace.md'},
                        {text: 'duk_to_stacktrace', link: '/resource/duktape/api/duk_to_stacktrace.md'},
                        {text: 'duk_cbor_decode', link: '/resource/duktape/api/duk_cbor_decode.md'},
                        {text: 'duk_cbor_encode', link: '/resource/duktape/api/duk_cbor_encode.md'},
                        {text: 'duk_pull', link: '/resource/duktape/api/duk_pull.md'},
                    ]
                },
                {
                    text: 'wiki',
                    collapsed: true,
                    items: [
                        {text: 'はじめに', link: '/resource/duktape/wiki/'},
                        {text: 'ライン処理', link: '/resource/duktape/wiki/process_lines.md'},
                        {text: 'プライマリーテスト', link: '/resource/duktape/wiki/prime_test.md'},
                        {text: '致命的なエラーの処理方法', link: '/resource/duktape/wiki/how_to_handle_fatal_errors.md'},
                        {text: '値スタック型の扱い方', link: '/resource/duktape/wiki/how_to_work_with_calue_stack_types.md'},
                        {text: '関数呼び出しの方法', link: '/resource/duktape/wiki/how_to_make_function_calls.md'},
                        {text: '仮想プロパティの使い方', link: '/resource/duktape/wiki/how_to_use_virtual_properties.md'},
                        {text: 'ファイナライゼーションの使い方', link: '/resource/duktape/wiki/how_to_use_finalization.md'},
                        {text: 'バッファの扱い方', link: '/resource/duktape/wiki/how_to_work_with_buffers_in_duktape_2x.md'},
                        {text: 'lightfuncsの使い方', link: '/resource/duktape/wiki/how_to_work_with_lightfuncs.md'},
                        {text: 'モジュールの使い方', link: '/resource/duktape/wiki/how_to_modules.md'},
                        {text: 'コルーチンの使い方', link: '/resource/duktape/wiki/how_to_coroutines.md'},
                        {text: 'ロギングの使い方', link: '/resource/duktape/wiki/how_to_use_logging.md'},
                        {text: 'ネイティブコードでオブジェクト参照を持続させる方法', link: '/resource/duktape/wiki/how_to_persist_object_references_in_native_code.md'},
                        {text: 'ネイティブのコンストラクタ関数の書き方', link: '/resource/duktape/wiki/how_to_write_a_native_constructor_function.md'},
                        {text: '配列の反復処理', link: '/resource/duktape/wiki/how_to_iterate_over_an_array.md'},
                        {text: 'エラー・オブジェクトを拡張する', link: '/resource/duktape/wiki/how_to_augment_error_objects.md'},
                        {text: 'Duktapeバイトコードのデコード方法', link: '/resource/duktape/wiki/how_to_decode_duktape_bytecode.md'},
                        {text: '非BMP文字を扱うには', link: '/resource/duktape/wiki/how_to_work_with_non-bmp_characters.md'},
                        {text: 'グローバル・オブジェクトへの参照を取得する方法', link: '/resource/duktape/wiki/how_to_get_a_reference_to_the_global_object.md'},
                        {text: 'ベアメタルプラットフォームで動作させる方法', link: '/resource/duktape/wiki/how_to_run_on_bare_metal_platforms.md'},
                        {text: 'デバッグ・プリントを有効にする方法', link: '/resource/duktape/wiki/how_to_enable_debug_prints.md'},
                        {text: 'Duktape用のエディターを設定する方法', link: '/resource/duktape/wiki/how_to_configure_your_editor_for_duktape.md'},
                        {text: 'Duktapeを開発するための設定', link: '/resource/duktape/wiki/development_setup_for_developing_duktape.md'},
                        {text: 'トラブルシューティングの基本', link: '/resource/duktape/wiki/troubleshooting_basics.md'},
                        {text: '内部プロトタイプと外部プロトタイプ', link: '/resource/duktape/wiki/internal_and_external_prototype.md'},
                        {text: 'API Cタイプ', link: '/resource/duktape/wiki/api_c_types.md'},
                        {text: 'ES5以降の機能', link: '/resource/duktape/wiki/post-es5_features.md'},
                        {text: 'ビルドのためのDuktapeの設定', link: '/resource/duktape/wiki/congifuring_duktape_for_build.md'},
                        {text: '設定オプション', link: '/resource/duktape/wiki/config_options.md'},
                        {text: '移植性', link: '/resource/duktape/wiki/portability.md'},
                        {text: 'TypeScriptとの互換性', link: '/resource/duktape/wiki/compatibility_with_typescript.md'},
                        {text: 'パフォーマンスを最適化する方法', link: '/resource/duktape/wiki/how_to_optimize_performance.md'},
                        {text: 'Duktapeを使ったプロジェクト', link: '/resource/duktape/wiki/projects_using_duktape.md'},
                        {text: 'デバッグ・クライアント', link: '/resource/duktape/wiki/debug_clients.md'},
                    ]
                },
                {
                    text: 'ドキュメント',
                    collapsed: true,
                    items: [
                        {text: 'API設計ガイドライン', link: '/resource/duktape/doc/api-design-guidelines.md'},
                        {text: '引数オブジェクト', link: '/resource/duktape/doc/arguments-object.md'},
                        {text: 'ベンチマークノート', link: '/resource/duktape/doc/benchmarking-notes.md'},
                        {text: 'バッファ', link: '/resource/duktape/doc/buffers.md'},
                        {text: 'バイトコード形式', link: '/resource/duktape/doc/bytecode.md'},
                        {text: 'Cモジュール規約', link: '/resource/duktape/doc/c-module-convention.md'},
                        {text: 'CBOR', link: '/resource/duktape/doc/cbor.md'},
                        {text: 'コードの問題', link: '/resource/duktape/doc/code-issues.md'},
                        {text: 'コンパイラ', link: '/resource/duktape/doc/compiler.md'},
                        {text: '日付と時刻', link: '/resource/duktape/doc/datetime.md'},
                        {text: 'デバッガ', link: '/resource/duktape/doc/debugger.md'},
                        {text: '設定ヘッダ', link: '/resource/duktape/doc/duk-config.md'},
                        {text: 'Emscriptenの互換性', link: '/resource/duktape/doc/emscripten-status.md'},
                        {text: 'エラーオブジェクト', link: '/resource/duktape/doc/error-objects.md'},
                        {text: '実行', link: '/resource/duktape/doc/execution.md'},
                        {text: 'Fastint型', link: '/resource/duktape/doc/fastint.md'},
                        {text: '関数テンプレート', link: '/resource/duktape/doc/function-objects.md'},
                        {text: 'Gitの規約', link: '/resource/duktape/doc/git-conventions.md'},
                        {text: 'defineProperties', link: '/resource/duktape/doc/hobject-alg-defineproperties.md'},
                        {text: 'defineProperty', link: '/resource/duktape/doc/hobject-alg-defineproperty.md'},
                        {text: 'DELPROP', link: '/resource/duktape/doc/hobject-alg-delprop.md'},
                        {text: 'Exotic behaviors', link: '/resource/duktape/doc/hobject-alg-exoticbehaviors.md'},
                        {text: 'getOwnPropertyDescriptor', link: '/resource/duktape/doc/hobject-alg-getownpropertydescriptor.md'},
                        {text: 'GETPROP', link: '/resource/duktape/doc/hobject-alg-getprop.md'},
                        {text: 'HASPROP', link: '/resource/duktape/doc/hobject-alg-hasprop.md'},
                        {text: 'INSTOF', link: '/resource/duktape/doc/hobject-alg-instof.md'},
                        {text: 'Preliminary algorithm work', link: '/resource/duktape/doc/hobject-alg-preliminaries.md'},
                        {text: 'PUTPROP', link: '/resource/duktape/doc/hobject-alg-putprop.md'},
                        {text: 'duk_hobject algorithms', link: '/resource/duktape/doc/hobject-algorithms.md'},
                        {text: 'duk_hobject', link: '/resource/duktape/doc/hobject-design.md'},
                        {text: 'Object enumeration issues', link: '/resource/duktape/doc/hobject-enumeration.md'},
                        {text: 'Identifier algorithms', link: '/resource/duktape/doc/identifier-handling.md'},
                        {text: 'JSON built-in', link: '/resource/duktape/doc/json.md'},
                        {text: 'Lightweight function value', link: '/resource/duktape/doc/lightweight-functions.md'},
                        {text: 'Duktape logging framework', link: '/resource/duktape/doc/logging.md'},
                        {text: 'Low memory environments', link: '/resource/duktape/doc/low-memory.md'},
                        {text: 'Memory management', link: '/resource/duktape/doc/memory-management.md'},
                        {text: 'Modules', link: '/resource/duktape/doc/modules.md'},
                        {text: 'Number-to-string and string-to-number conversions', link: '/resource/duktape/doc/number-conversion.md'},
                        {text: 'Moving objects to code section', link: '/resource/duktape/doc/objects-in-code-section.md'},
                        {text: 'Performance sensitive environments', link: '/resource/duktape/doc/performance-sensitive.md'},
                        {text: 'Regular expressions', link: '/resource/duktape/doc/regexp.md'},
                        {text: 'リリースチェックリスト', link: '/resource/duktape/doc/release-checklist.md'},
                        {text: 'Duktape 1.0 リリースノート', link: '/resource/duktape/doc/release-notes-v1-0.md'},
                        {text: 'Duktape 1.1 リリースノート', link: '/resource/duktape/doc/release-notes-v1-1.md'},
                        {text: 'Duktape 1.2 リリースノート', link: '/resource/duktape/doc/release-notes-v1-2.md'},
                        {text: 'Duktape 1.3 リリースノート', link: '/resource/duktape/doc/release-notes-v1-3.md'},
                        {text: 'Duktape 1.4 リリースノート', link: '/resource/duktape/doc/release-notes-v1-4.md'},
                        {text: 'Duktape 1.5 リリースノート', link: '/resource/duktape/doc/release-notes-v1-5.md'},
                        {text: 'Duktape 1.6 リリースノート', link: '/resource/duktape/doc/release-notes-v1-6.md'},
                        {text: 'Duktape 2.0 リリースノート', link: '/resource/duktape/doc/release-notes-v2-0.md'},
                        {text: 'Duktape 2.1 リリースノート', link: '/resource/duktape/doc/release-notes-v2-1.md'},
                        {text: 'Duktape 2.2 リリースノート', link: '/resource/duktape/doc/release-notes-v2-2.md'},
                        {text: 'Duktape 2.3 リリースノート', link: '/resource/duktape/doc/release-notes-v2-3.md'},
                        {text: 'Duktape 2.4 リリースノート', link: '/resource/duktape/doc/release-notes-v2-4.md'},
                        {text: 'Duktape 2.5 リリースノート', link: '/resource/duktape/doc/release-notes-v2-5.md'},
                        {text: 'Duktape 2.6 リリースノート', link: '/resource/duktape/doc/release-notes-v2-6.md'},
                        {text: 'Duktape 2.7 リリースノート', link: '/resource/duktape/doc/release-notes-v2-7.md'},
                        {text: 'Duktape 3.0 リリースノート', link: '/resource/duktape/doc/release-notes-v3-0.md'},
                        {text: 'reStructuredText conventions', link: '/resource/duktape/doc/rst-conventions.md'},
                        {text: 'Sandboxing Duktape', link: '/resource/duktape/doc/sandboxing.md'},
                        {text: 'Side effects', link: '/resource/duktape/doc/side-effects.md'},
                        {text: 'ソート', link: '/resource/duktape/doc/sorting.md'},
                        {text: 'String table', link: '/resource/duktape/doc/string-table.md'},
                        {text: 'ES2015 Symbols in Duktape 2.x', link: '/resource/duktape/doc/symbols.md'},
                        {text: 'Installing Duktape as a system library', link: '/resource/duktape/doc/system-install.md'},
                        {text: 'Status of test262 testcases', link: '/resource/duktape/doc/test262-status.md'},
                        {text: 'Testcases', link: '/resource/duktape/doc/testcases.md'},
                        {text: 'Duktape threading', link: '/resource/duktape/doc/threading.md'},
                        {text: 'タイミングに敏感な環境', link: '/resource/duktape/doc/timing-sensitive.md'},
                        {text: 'Duktape typing', link: '/resource/duktape/doc/types.md'},
                        {text: 'Status of underscore testcases', link: '/resource/duktape/doc/underscore-status.md'},
                        {text: 'Unicode support', link: '/resource/duktape/doc/unicode-support.md'},
                        {text: 'URI encoding and decoding', link: '/resource/duktape/doc/uri.md'},
                        {text: 'Using UTF-8 as internal representation', link: '/resource/duktape/doc/utf8-internal-representation.md'},
                        {text: 'Value stack resizing', link: '/resource/duktape/doc/value-stack-resizing.md'},
                    ],
                },
      ],
      '/resource/glfw/': [
        {
          text: 'GLFW',
          collapsed: false,
          items: [
            {text: 'はじめに', link: '/resource/glfw/'},
            {text: 'イントロダクション', link: '/resource/glfw/introduction.md'},
            {text: 'チュートリアル', link: '/resource/glfw/tutorial/'},
          ]
        },
        {
          text: 'プログラミングガイド',
          collapsed: false,
          items: [
            {text: 'API入門', link: '/resource/glfw/guides/introduction_to_the_api.md'},
            {text: 'ウィンドウガイド', link: '/resource/glfw/guides/window_guide.md'},
            {text: 'コンテキストガイド', link: '/resource/glfw/guides/context_guide.md'},
            {text: 'モニターガイド', link: '/resource/glfw/guides/monitor_guide.md'},
            {text: '入力ガイド', link: '/resource/glfw/guides/input_guide.md'},
          ]
        },
        {
          text: 'リファレンス',
          collapsed: false,
          items: [
            {text: '目次', link: '/resource/glfw/reference/'},
            {text: 'コンテキスト', link: '/resource/glfw/reference/context.md'},
            {text: '初期化など', link: '/resource/glfw/reference/init.md'},
            {text: 'エラーコード', link: '/resource/glfw/reference/error.md'},
            {text: '入力', link: '/resource/glfw/reference/input.md'},
            {text: 'ゲームパッドの軸', link: '/resource/glfw/reference/gamepad_axes.md'},
            {text: 'ゲームパッドのボタン', link: '/resource/glfw/reference/gamepad_buttons.md'},
            {text: 'ジョイスティックのハット', link: '/resource/glfw/reference/joystick_hat_states.md'},
            {text: 'ジョイスティック', link: '/resource/glfw/reference/joysticks.md'},
            {text: 'キーボードのキー', link: '/resource/glfw/reference/keyboard_keys.md'},
            {text: '修飾キー', link: '/resource/glfw/reference/modifier_key_flags.md'},
            {text: 'マウスボタン', link: '/resource/glfw/reference/mouse_buttons.md'},
            {text: 'カーソルの形状', link: '/resource/glfw/reference/standard_cursor_shapes.md'},
            {text: 'モニター', link: '/resource/glfw/reference/monitor.md'},
            {text: 'ネイティブアクセス', link: '/resource/glfw/reference/native.md'},
            {text: 'Vulkanサポート', link: '/resource/glfw/reference/vulkan.md'},
            {text: 'ウィンドウ', link: '/resource/glfw/reference/window.md'},
          ]
        },
      ],
      '/resource/imgui/': [
        {
          text: 'はじめに',
          collapsed: false,
          items: [
            {text: 'ImGUI', link: '/resource/imgui/'},
          ]
        },
        {
          text: 'ドキュメント',
          collapsed: false,
          items: [
            {text: 'バックエンド', link: '/resource/imgui/backends.md'},
            {text: '更新履歴', link: '/resource/imgui/changelog.md'},
            {text: '貢献する', link: '/resource/imgui/contributing.md'},
            {text: 'サンプルコード', link: '/resource/imgui/examples.md'},
            {text: 'よくある質問', link: '/resource/imgui/faq.md'},
            {text: 'フォント', link: '/resource/imgui/fonts.md'},
            {text: 'ToDo', link: '/resource/imgui/todo.md'},
          ]
        },
        {
          text: 'ヘッダーファイル',
          collapsed: false,
          items: [
            {text: 'imgui.h', link: '/resource/imgui/imgui_h.md'},
          ]
        }
      ],
      '/resource/libffi/': [
        {
          text: 'はじめに',
          collapsed: false,
          items: [
            {text: 'libffi', link: '/resource/libffi/'},
            {text: 'マニュアル', link: '/resource/libffi/manual'},
          ]
        },
      ],
      '/resource/lua/': [
        {
          text: 'はじめに',
          collapsed: false,
          items: [
            {text: 'Luaについて', link: '/resource/lua/'},
            {text: 'お問い合わせ', link: '/resource/lua/contact'},
          ]
        },
        {
          text: 'Luaの紹介',
          collapsed: false,
          items: [
            {text: 'ニュース', link: '/resource/lua/news'},
            {text: 'ショーケース', link: '/resource/lua/showcase'},
            {text: '活用事例', link: '/resource/lua/uses'},
            {text: '引用集', link: '/resource/lua/quotes'},
            {text: 'プレス記事', link: '/resource/lua/press'},
            {text: '開発者', link: '/resource/lua/authors'},
            {text: '謝辞', link: '/resource/lua/thanks'},
          ]
        },
        {
          text: 'ダウンロード',
          collapsed: false,
          items: [
            {text: 'ダウンロード', link: '/resource/lua/download'},
            {text: 'ライセンス', link: '/resource/lua/license'},
            {text: 'デモ', link: '/resource/lua/demo'},
          ]
        },
        {
          text: 'ドキュメント',
          collapsed: false,
          items: [
            {text: 'ドキュメント', link: '/resource/lua/documentation'},
            {text: 'はじめに', link: '/resource/lua/getting_started'},
            {
              text: 'リファレンス',
              collapsed: false,
              items: [
                {text:'リファレンス', link:'/resource/lua/reference_manual'},
                {text:'5.4 マニュアル', link:'/resource/lua/5.4_manual'},
                {text:'5.3 マニュアル', link:'/resource/lua/5.3_manual'},
                {text:'5.2 マニュアル', link:'/resource/lua/5.2_manual'},
                {text:'5.1 マニュアル', link:'/resource/lua/5.1_manual'},
              ]
            },
            {text: 'FAQ', link: '/resource/lua/faq'},
            {text: 'バージョン履歴', link: '/resource/lua/versions'},
          ]
        },
        {
          text: 'コミュニティ',
          collapsed: false,
          items: [
              {text: 'コミュニティ', link: '/resource/lua/community'},
          ]
        },
      ],
      '/resource/luajit/': [
        {
          text: 'LuaJIT',
          collapsed: false,
          items: [
            {text: 'ホーム', link: '/resource/luajit/'},
            {text: 'LuaJIT', link: '/resource/luajit/luajit'},
            {text: 'ダウンロード', link: '/resource/luajit/download'},
            {text: 'インストール', link: '/resource/luajit/installation'},
            {text: '実行する', link: '/resource/luajit/running'},
            {text: '拡張機能', link: '/resource/luajit/extensions'},
            {text: 'FFIライブラリ', link: '/resource/luajit/ffi_library'},
            {text: 'FFIチュートリアル', link: '/resource/luajit/ffi_tutorial'},
            {text: 'ffi.* API', link: '/resource/luajit/ffi_api'},
            {text: 'FFIセマンティクス', link: '/resource/luajit/ffi_semantics'},
            {text: 'String Buffers', link: '/resource/luajit/string_buffers'},
            {text: 'jit.* Library', link: '/resource/luajit/jit_library'},
            {text: 'Lua/C API', link: '/resource/luajit/lua_c_api'},
            {text: 'プロファイラ', link: '/resource/luajit/profiler'},
            {text: 'ステータス', link: '/resource/luajit/status'},
            {text: 'FAQ', link: '/resource/luajit/faq'},
            {text: 'メーリングリスト', link: '/resource/luajit/mailing_list'},
            {text: 'スポンサー', link: '/resource/luajit/sponsors'},
          ]
        },
      ],
      '/resource/miniaudio/': [
        {
          text: 'miniaudio',
          collapsed: false,
          items: [
            {text: 'はじめに', link: '/resource/miniaudio/'},
            {text: 'マニュアル', link: '/resource/miniaudio/programming_manual.md'},
            {text: 'サンプル', link: '/resource/miniaudio/example.md'},
          ]
        },
      ],
      '/resource/skia/': [
        {
          text: 'はじめに',
          collapsed: false,
          items: [
            {text: 'Skia', link: '/resource/skia/'},
          ]
        },
        {
          text: '入手とビルド',
          collapsed: false,
          items: [
            {text: 'Skiaのダウンロード方法', link: '/resource/skia/how_to_download_skia.md'},
            {text: 'Skiaのビルド方法', link: '/resource/skia/how_to_build_skia.md'},
          ]
        },
        {
          text: 'gnファイル',
          collapsed: false,
          items: [
            {text: 'skia/BUILD.gn', link: '/resource/skia/skia_build_gn.md'},
            {text: 'skia/gn/BUILDCONFIG.gn', link: '/resource/skia/skia_gn_buildconfig_gn.md'},
            {text: 'skia/gn/skia.gni', link: '/resource/skia/skia_gn_skia_gni.md'},
            {text: 'skia/gn/skia/BUILD.gn', link: '/resource/skia/skia_gn_skia_build_gn.md'},
            {text: 'skia/gn/toolchain/BUILD.gn', link: '/resource/skia/skia_gn_toolchain_build_gn.md'},
          ]
        },
      ],
      '/resource/stb/': [
        {
          text: 'はじめに',
          collapsed: false,
          items: [
            {text: 'stb', link: '/resource/stb/'},
            {text: 'シングルファイル', link: '/resource/stb/single_file_libs.md'},
            {text: 'パブリックドメイン', link: '/resource/stb/why_public_domain.md'},
          ]
        },
        {
          text: 'ヘッダーファイル',
          collapsed: false,
          items: [
            {text: 'stb_image.h', link: '/resource/stb/stb_image_h.md'},
            {text: 'stb_truetype.h', link: '/resource/stb/stb_truetype_h.md'},
          ]
        },
      ],
      '/resource/terra/': [
        {
          text: 'Terra',
          collapsed: false,
          items: [
            {text: 'トップ', link: '/resource/terra/'},
            {text: 'はじめに', link: '/resource/terra/getting-started.md'},
            {text: 'APIリファレンス', link: '/resource/terra/api.md'},
            {text: 'Terra for C++', link: '/resource/terra/terraforcpp.md'},
            {text: '出版物', link: '/resource/terra/publications.md'},
            {text: 'コミュニティ', link: '/resource/terra/community.md'},
          ]
        },
      ],
      '/resource/uthash/': [
        {
          text: 'はじめに',
          collapsed: false,
          items: [
            {text: 'uthash', link: '/resource/uthash/'},
          ]
        },
        {
          text: 'マニュアル',
          collapsed: false,
          items: [
            {text: 'uthash', link: '/resource/uthash/uthash.md'},
            {text: 'utlist', link: '/resource/uthash/utlist.md'},
            {text: 'utarray', link: '/resource/uthash/utarray.md'},
            {text: 'utringbuffer', link: '/resource/uthash/utringbuffer.md'},
            {text: 'utstack', link: '/resource/uthash/utstack.md'},
            {text: 'utstring', link: '/resource/uthash/utstring.md'},
          ]
        },
      ],
      '/resource/yyjson/': [
        {
          text: 'はじめに',
          collapsed: false,
          items: [
            {text: 'yyjson', link: '/resource/yyjson/'},
            {text: '構築とテスト', link: '/resource/yyjson/BuildAndTest.md'},
            {text: 'API', link: '/resource/yyjson/API.md'},
            {text: 'データ構造', link: '/resource/yyjson/DataStructure.md'},
            {text: '更新履歴', link: '/resource/yyjson/CHANGELOG.md'},
          ]
        },
      ],
    },
  }
})
